### ISSUE TITLE
The message "NOTE: We are formalizing our plans to enter AWS SDK for JavaScript" causes the retrieval job to fail. 

### ISSUE THREAD

**Issue by JonasPospichal** [akeyless-community/akeyless-github-action#14]
Hello,

When using this configuration of the GitHub Action:

```
Run akeyless-community/akeyless-github-action@v1.0.1
  with:
    access-id: ***
    static-secrets: - name: "￭￭￭￭"
    output-name: "￭￭￭"
  
    export-secrets-to-environment: true
    export-secrets-to-outputs: false
    access-type: jwt
    api-url: https://api.akeyless.io
    gcp-audience: akeyless.io
```

, I have encountered the following error:

```
(node:1551) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v[2](https://github.com/￭￭￭/￭￭￭/actions/runs/10117642212/job/27983039247#step:3:2)) into maintenance mode in 202[3](https://github.com/￭￭￭/￭￭￭/actions/runs/10117642212/job/27983039247#step:3:3).

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/[7](https://github.com/￭￭￭/￭￭￭/actions/runs/10117642212/job/27983039247#step:3:7)PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Error: get secret value Failed
```

Has anyone else encountered this error too? It causes the whole retrieval job to fail.

Thanks,

Jonáš.
